; generated by PrusaSlicer 2.3.0+win64 on 2021-05-04 at 14:56:26 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R1
M73 Q0 S1
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.9.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 P5 R1
M73 Q5 S1
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95

; Don't change E values below. Excessive value can damage the printer.
M907 E430 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P8 R1
M73 Q8 S1
G1 E-0.80000 F2100.000
G1 Z0.400 F10800.000
;AFTER_LAYER_CHANGE
;0.2
G1 X64.207 Y54.099
M73 P9 R1
M73 Q9 S1
G1 Z0.200
G1 E0.80000 F2100.000
M204 S1000
;TYPE:Skirt
;WIDTH:0.42
G1 F1200.000
G1 X65.065 Y53.082 E0.04172
M73 Q10 S1
G1 X68.168 Y49.889 E0.13960
M73 P10 R1
G1 X73.270 Y45.147 E0.21841
G1 X75.565 Y43.191 E0.09455
M73 Q11 S1
G1 X77.716 Y41.559 E0.08466
M73 P11 R1
G1 X79.937 Y40.054 E0.08411
G1 X82.234 Y38.669 E0.08411
G1 X84.602 Y37.408 E0.08411
G1 X87.243 Y36.186 E0.09125
G1 X89.967 Y35.111 E0.09180
M73 P12 R1
M73 Q12 S1
G1 X92.732 Y34.202 E0.09125
G1 X95.545 Y33.454 E0.09125
G1 X98.396 Y32.870 E0.09125
G1 X101.276 Y32.451 E0.09125
M73 Q13 S1
G1 X104.193 Y32.198 E0.09180
M73 P13 R1
G1 X107.102 Y32.115 E0.09125
G1 X109.433 Y32.170 E0.07312
G1 X111.777 Y32.334 E0.07367
G1 X114.093 Y32.605 E0.07312
G1 X116.412 Y32.987 E0.07367
M73 Q14 S1
G1 X158.534 Y41.815 E1.34942
M73 P17 R1
M73 Q17 S1
G1 X162.137 Y42.795 E0.11708
G1 X165.658 Y44.039 E0.11708
G1 X169.077 Y45.541 E0.11708
G1 X172.375 Y47.291 E0.11708
M73 P18 R1
M73 Q18 S1
G1 X174.821 Y48.803 E0.09015
G1 X177.177 Y50.452 E0.09015
G1 X179.434 Y52.232 E0.09015
G1 X181.587 Y54.139 E0.09015
G1 X183.627 Y56.165 E0.09015
M73 P19 R1
M73 Q19 S1
G1 X185.549 Y58.304 E0.09015
G1 X187.345 Y60.549 E0.09015
G1 X189.010 Y62.894 E0.09015
G1 X190.538 Y65.329 E0.09015
G1 X191.926 Y67.847 E0.09015
M73 P20 R1
M73 Q20 S1
G1 X193.167 Y70.441 E0.09015
G1 X194.258 Y73.101 E0.09015
G1 X195.196 Y75.819 E0.09015
G1 X195.977 Y78.587 E0.09015
G1 X196.599 Y81.394 E0.09015
M73 P21 R1
M73 Q21 S1
G1 X197.060 Y84.232 E0.09015
G1 X197.366 Y87.197 E0.09345
G1 X197.496 Y90.175 E0.09345
G1 X197.449 Y93.155 E0.09345
G1 X197.227 Y96.127 E0.09345
M73 P22 R1
M73 Q22 S1
G1 X196.829 Y99.081 E0.09345
G1 X196.257 Y102.006 E0.09345
G1 X195.513 Y104.892 E0.09345
G1 X194.600 Y107.729 E0.09345
M73 Q23 S1
G1 X193.743 Y109.973 E0.07532
M73 P23 R1
G1 X192.788 Y112.158 E0.07477
G1 X191.722 Y114.311 E0.07532
G1 X190.563 Y116.395 E0.07477
G1 X181.821 Y130.064 E0.50874
M73 P24 R1
M73 Q24 S1
G1 X179.745 Y133.019 E0.11323
M73 P25 R1
M73 Q25 S1
G1 X158.473 Y159.794 E1.07221
M73 P27 R1
M73 Q27 S1
G1 X156.973 Y161.510 E0.07147
G1 X155.410 Y163.145 E0.07092
G1 X153.762 Y164.720 E0.07147
G1 X152.044 Y166.218 E0.07147
M73 P28 R1
M73 Q28 S1
G1 X149.246 Y168.388 E0.11104
G1 X146.302 Y170.357 E0.11104
G1 X143.227 Y172.113 E0.11104
G1 X140.036 Y173.649 E0.11104
M73 P29 R1
M73 Q29 S1
G1 X136.745 Y174.958 E0.11104
G1 X133.371 Y176.031 E0.11104
G1 X129.929 Y176.865 E0.11104
G1 X126.437 Y177.456 E0.11104
M73 P30 R1
M73 Q30 S1
G1 X122.895 Y177.800 E0.11159
G1 X119.337 Y177.894 E0.11159
G1 X115.782 Y177.736 E0.11159
G1 X112.247 Y177.328 E0.11159
M73 P31 R1
M73 Q31 S1
G1 X108.749 Y176.671 E0.11159
G1 X105.323 Y175.773 E0.11104
G1 X101.952 Y174.631 E0.11159
G1 X98.671 Y173.254 E0.11159
M73 P32 R1
M73 Q32 S1
G1 X95.771 Y171.800 E0.10170
G1 X92.987 Y170.172 E0.10115
G1 X90.297 Y168.359 E0.10170
G1 X87.744 Y166.388 E0.10115
M73 P33 R1
M73 Q33 S1
G1 X85.993 Y164.875 E0.07257
G1 X84.325 Y163.295 E0.07202
G1 X76.820 Y155.731 E0.33410
M73 P34 R1
M73 Q34 S1
G1 X74.915 Y153.671 E0.08796
G1 X73.432 Y151.894 E0.07257
G1 X72.033 Y150.051 E0.07257
G1 X70.719 Y148.146 E0.07257
G1 X69.503 Y146.197 E0.07202
G1 X68.369 Y144.179 E0.07257
M73 P35 R1
M73 Q35 S1
G1 X67.329 Y142.112 E0.07257
G1 X66.385 Y139.998 E0.07257
G1 X65.539 Y137.844 E0.07257
G1 X64.602 Y135.033 E0.09290
G1 X54.272 Y100.418 E1.13264
M73 P38 R1
M73 Q38 S1
G1 X53.389 Y96.844 E0.11543
G1 X52.770 Y93.215 E0.11543
G1 X52.486 Y90.530 E0.08466
M73 P39 R1
M73 Q39 S1
G1 X52.345 Y87.816 E0.08521
G1 X52.350 Y85.116 E0.08466
G1 X52.501 Y82.402 E0.08521
G1 X52.796 Y79.719 E0.08466
G1 X53.235 Y77.054 E0.08466
M73 P40 R1
G1 X53.815 Y74.417 E0.08466
M73 Q40 S1
G1 X54.541 Y71.799 E0.08521
G1 X55.401 Y69.239 E0.08466
G1 X56.404 Y66.713 E0.08521
G1 X57.534 Y64.261 E0.08466
M73 P41 R1
G1 X58.794 Y61.873 E0.08466
M73 Q41 S1
G1 X60.189 Y59.541 E0.08521
G1 X61.698 Y57.302 E0.08466
G1 X63.325 Y55.147 E0.08466
G1 X64.169 Y54.145 E0.04106
; printing object body6968374 id:0 copy 0
;WIPE_START
G1 F8640.000
G1 X65.065 Y53.082 E-0.32108
G1 X66.390 Y51.719 E-0.43892
;WIPE_END
M73 P42 R1
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
M73 Q42 S1
G1 X121.792 Y97.287
G1 Z0.200
M73 P43 R1
M73 Q43 S1
G1 E0.80000 F2100.000
;TYPE:Perimeter
G1 F1200.000
G1 X122.937 Y97.029 E0.03680
G1 X122.921 Y97.576 E0.01715
G1 X121.850 Y97.302 E0.03466
;WIPE_START
G1 F8640.000
G1 X122.937 Y97.029 E-0.25874
G1 X122.921 Y97.576 E-0.12630
G1 X121.850 Y97.302 E-0.25528
;WIPE_END
G1 E-0.15968 F2100.000
G1 Z0.600 F10800.000
G1 X120.364 Y96.810
G1 Z0.200
G1 E0.80000 F2100.000
G1 F1200.000
G1 X119.491 Y96.289 E0.03187
M73 Q44 S1
G1 X117.500 Y95.173 E0.07156
M73 P44 R1
G1 X118.031 Y94.489 E0.02713
G1 X120.321 Y96.767 E0.10129
;WIPE_START
G1 F8640.000
G1 X119.491 Y96.289 E-0.22129
G1 X117.500 Y95.173 E-0.52698
G1 X117.531 Y95.133 E-0.01173
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X121.201 Y97.503
G1 Z0.200
M73 Q45 S1
G1 E0.80000 F2100.000
M73 P45 R1
G1 F1200.000
G1 X121.350 Y97.399 E0.00572
G1 X121.336 Y97.390 E0.00053
G1 X121.697 Y97.309 E0.01161
G1 X121.283 Y97.746 E0.01888
G1 X121.220 Y97.560 E0.00617
G1 X121.621 Y97.939 F10800.000
;TYPE:External perimeter
G1 F1200.000
G1 X121.853 Y97.692 E0.01063
G1 X134.152 Y100.837 E0.39801
M73 P46 R1
M73 Q46 S1
G1 X136.122 Y101.361 E0.06392
G1 X127.351 Y114.918 E0.50626
M73 P47 R1
M73 Q47 S1
G1 X126.836 Y114.848 E0.01630
G1 X121.522 Y98.043 E0.55262
M73 P48 R1
M73 Q48 S1
G1 X121.579 Y97.982 E0.00262
G1 X121.418 Y97.667 F10800.000
G1 X120.878 Y97.725
G1 F1200.000
G1 X121.513 Y99.597 E0.06196
M73 Q49 S1
G1 X125.942 Y113.609 E0.46079
M73 P50 R1
M73 Q50 S1
G1 X126.286 Y114.803 E0.03895
G1 X125.874 Y115.126 E0.01643
G1 X116.369 Y109.272 E0.35000
G1 X115.505 Y108.785 E0.03110
M73 P51 R1
M73 Q51 S1
G1 X109.956 Y105.362 E0.20440
G1 X120.829 Y97.760 E0.41598
M73 P52 R1
M73 Q52 S1
G1 X121.210 Y97.503 F10800.000
;WIPE_START
G1 F8640.000
G1 X121.513 Y99.597 E-0.45259
G1 X121.914 Y100.866 E-0.30741
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X115.566 Y109.220
M73 P53 R1
M73 Q53 S1
G1 Z0.200
G1 E0.80000 F2100.000
G1 F1200.000
G1 X125.320 Y115.229 E0.35920
G1 X125.973 Y115.606 E0.02364
M73 P54 R1
M73 Q54 S1
G1 X125.912 Y116.115 E0.01609
G1 X115.696 Y119.458 E0.33704
G1 X113.672 Y120.084 E0.06641
G1 X115.164 Y111.182 E0.28302
M73 P55 R1
M73 Q55 S1
G1 X115.346 Y110.204 E0.03119
G1 X115.553 Y109.279 E0.02973
G1 X115.735 Y108.857 F10800.000
;WIPE_START
G1 F8640.000
G1 X118.364 Y110.991 E-0.76000
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
M73 P56 R1
M73 Q56 S1
G1 X126.235 Y115.322
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:Perimeter
G1 F1200.000
G1 X126.520 Y115.099 E0.01132
G1 X126.548 Y115.189 E0.00296
G1 X127.155 Y115.272 E0.01921
G1 X126.759 Y115.887 E0.02295
G1 X126.301 Y116.035 E0.01508
G1 X126.377 Y115.404 E0.01995
G1 X126.287 Y115.352 E0.00325
;WIPE_START
G1 F8640.000
G1 X126.520 Y115.099 E-0.07923
G1 X126.548 Y115.189 E-0.02183
G1 X127.155 Y115.272 E-0.14145
G1 X126.759 Y115.887 E-0.16900
G1 X126.301 Y116.035 E-0.11107
G1 X126.377 Y115.404 E-0.14694
G1 X126.287 Y115.352 E-0.02396
;WIPE_END
M73 P57 R1
G1 E-0.10652 F2100.000
G1 Z0.600 F10800.000
M73 Q57 S1
G1 X119.039 Y118.801
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:External perimeter
G1 F1200.000
G1 X119.039 Y124.959 E0.19307
M73 P57 R0
G1 X118.578 Y125.149 E0.01566
M73 P58 R0
M73 Q57 S0
G1 X117.708 Y124.311 E0.03787
M73 Q58 S0
G1 X113.876 Y120.451 E0.17053
G1 X118.140 Y119.066 E0.14057
G1 X118.982 Y118.818 E0.02751
G1 X119.437 Y118.760 F10800.000
;WIPE_START
G1 F8640.000
G1 X119.013 Y122.110 E-0.76000
;WIPE_END
M73 P59 R0
M73 Q59 S0
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X119.030 Y125.371
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:Perimeter
G1 F1200.000
G1 X119.048 Y125.718 E0.01089
G1 X118.824 Y125.455 E0.01080
G1 X118.974 Y125.394 E0.00508
;WIPE_START
G1 F8640.000
G1 X119.048 Y125.718 E-0.07672
G1 X118.824 Y125.455 E-0.07956
G1 X118.974 Y125.394 E-0.03743
;WIPE_END
G1 E-0.60630 F2100.000
G1 Z0.600 F10800.000
G1 X104.195 Y88.560
M73 P60 R0
M73 Q60 S0
G1 Z0.200
G1 E0.80000 F2100.000
G1 F1200.000
G1 X104.020 Y88.125 E0.01471
G1 X104.430 Y88.367 E0.01493
G1 X104.241 Y88.522 E0.00766
G1 X104.480 Y88.814 F10800.000
;TYPE:External perimeter
G1 F1200.000
G1 X104.805 Y88.547 E0.01317
G1 X108.068 Y90.330 E0.11658
M73 Q61 S0
G1 X118.436 Y96.128 E0.37248
M73 P61 R0
G1 X119.302 Y96.615 E0.03113
G1 X120.656 Y97.424 E0.04946
M73 P62 R0
M73 Q62 S0
G1 X109.686 Y105.083 E0.41949
M73 Q63 S0
G1 X106.233 Y94.595 E0.34621
M73 P63 R0
G1 X104.753 Y90.030 E0.15046
M73 P64 R0
M73 Q64 S0
G1 X104.417 Y88.865 E0.03800
G1 X104.434 Y88.852 E0.00067
G1 X104.277 Y88.469 F10800.000
;WIPE_START
G1 F8640.000
G1 X104.805 Y88.547 E-0.11087
G1 X107.272 Y89.895 E-0.64913
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X107.868 Y89.791
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:Perimeter
G1 F1200.000
G1 X107.894 Y89.778 E0.00091
;WIPE_START
G1 F8640.000
G1 X107.894 Y89.778 E0.00000
;WIPE_END
G1 E-0.80000 F2100.000
G1 Z0.600 F10800.000
G1 X107.992 Y85.235
M73 P65 R0
M73 Q65 S0
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:External perimeter
G1 F1200.000
G1 X108.463 Y85.024 E0.01618
G1 X109.370 Y85.897 E0.03946
G1 X117.649 Y94.366 E0.37135
M73 P66 R0
M73 Q66 S0
G1 X117.165 Y94.990 E0.02477
G1 X108.286 Y90.023 E0.31897
G1 X107.996 Y85.295 E0.14852
M73 P67 R0
M73 Q67 S0
G1 X107.789 Y84.890 F10800.000
G1 X107.990 Y84.822
;TYPE:Perimeter
G1 F1200.000
G1 X107.943 Y84.405 E0.01316
G1 X108.220 Y84.719 E0.01313
G1 X108.045 Y84.798 E0.00602
;WIPE_START
G1 F8640.000
G1 X107.943 Y84.405 E-0.09363
G1 X108.220 Y84.719 E-0.09667
G1 X108.045 Y84.798 E-0.04434
;WIPE_END
G1 E-0.56536 F2100.000
G1 Z0.600 F10800.000
G1 X123.317 Y96.944
M73 P68 R0
M73 Q68 S0
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:External perimeter
G1 F1200.000
G1 X145.082 Y92.038 E0.69957
M73 P69 R0
M73 Q69 S0
G1 X145.323 Y92.382 E0.01315
G1 X139.328 Y101.679 E0.34686
M73 P70 R0
M73 Q70 S0
G1 X138.602 Y101.527 E0.02325
G1 X137.150 Y101.159 E0.04697
G1 X135.690 Y100.827 E0.04694
G1 X123.296 Y97.656 E0.40112
M73 P71 R0
M73 Q71 S0
G1 X123.315 Y97.004 E0.02044
G1 X123.101 Y96.607 F10800.000
;WIPE_START
G1 F8640.000
G1 X126.524 Y96.272 E-0.76000
;WIPE_END
M73 P72 R0
M73 Q72 S0
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X145.488 Y91.960
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:Perimeter
G1 F1200.000
G1 X145.634 Y91.918 E0.00478
G1 X145.543 Y92.040 E0.00476
G1 X145.522 Y92.010 E0.00115
;WIPE_START
G1 F8640.000
G1 X145.634 Y91.918 E-0.03337
G1 X145.543 Y92.040 E-0.03503
G1 X145.522 Y92.010 E-0.00845
;WIPE_END
G1 E-0.72315 F2100.000
G1 Z0.600 F10800.000
M73 P73 R0
M73 Q73 S0
G1 X121.138 Y97.048
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:External perimeter
G1 F1200.000
G1 X144.748 Y91.728 E0.75884
M73 P75 R0
M73 Q75 S0
G1 X145.246 Y91.638 E0.01587
G1 X145.749 Y91.492 E0.01641
G1 X146.211 Y91.299 E0.01570
G1 X146.671 Y91.198 E0.01474
G1 X146.419 Y91.590 E0.01459
G1 X146.079 Y91.954 E0.01562
G1 X145.766 Y92.371 E0.01634
G1 X145.508 Y92.804 E0.01583
G1 X139.847 Y101.571 E0.32719
M73 P76 R0
M73 Q76 S0
G1 X139.431 Y102.146 E0.02227
G1 X136.578 Y101.398 E0.09248
G1 X135.619 Y102.833 E0.05412
G1 X127.003 Y116.204 E0.49873
M73 P77 R0
M73 Q77 S0
G1 X119.392 Y118.676 E0.25093
M73 P78 R0
M73 Q78 S0
G1 X119.416 Y119.441 E0.02399
G1 X119.416 Y124.663 E0.16372
G1 X119.398 Y125.142 E0.01504
G1 X119.417 Y125.636 E0.01552
G1 X119.489 Y126.129 E0.01560
G1 X119.582 Y126.589 E0.01473
M73 Q79 S0
G1 X119.582 Y127.009 E0.01317
M73 P79 R0
G1 X119.261 Y126.686 E0.01427
G1 X118.995 Y126.275 E0.01536
G1 X118.685 Y125.863 E0.01615
G1 X118.343 Y125.487 E0.01593
G1 X113.275 Y120.370 E0.22583
G1 X113.457 Y119.095 E0.04038
G1 X114.857 Y110.729 E0.26594
M73 P80 R0
M73 Q80 S0
G1 X115.122 Y108.991 E0.05512
G1 X110.525 Y106.165 E0.16919
G1 X109.464 Y105.484 E0.03954
G1 X109.163 Y104.697 E0.02641
M73 P81 R0
M73 Q81 S0
G1 X106.072 Y95.326 E0.30939
G1 X103.872 Y88.769 E0.21686
M73 P82 R0
M73 Q82 S0
G1 X103.684 Y88.296 E0.01597
G1 X103.454 Y87.837 E0.01610
G1 X103.212 Y87.413 E0.01530
G1 X103.074 Y87.001 E0.01363
G1 X103.454 Y87.206 E0.01355
G1 X103.830 Y87.516 E0.01527
G1 X104.244 Y87.821 E0.01611
G1 X104.685 Y88.079 E0.01603
G1 X105.129 Y88.298 E0.01554
G1 X107.484 Y89.588 E0.08420
G1 X107.870 Y89.343 E0.01434
G1 X107.650 Y85.795 E0.11146
M73 P83 R0
M73 Q83 S0
G1 X107.613 Y84.839 E0.03000
G1 X107.557 Y84.347 E0.01554
G1 X107.345 Y83.412 E0.03004
G1 X107.323 Y83.029 E0.01204
G1 X107.801 Y83.543 E0.02203
G1 X108.030 Y83.915 E0.01368
G1 X108.358 Y84.317 E0.01628
G1 X108.707 Y84.684 E0.01585
G1 X121.096 Y97.006 E0.54787
M73 P84 R0
M73 Q84 S0
G1 X121.298 Y97.415 F10800.000
;WIPE_START
G1 F8640.000
G1 X124.308 Y96.289 E-0.76000
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X121.257 Y98.049
M73 P85 R0
M73 Q85 S0
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:Gap fill
;WIDTH:0.144326
G1 F1200.000
G1 X121.740 Y99.523 E0.01308
G1 X126.172 Y113.541 E0.12396
;WIDTH:0.177096
M73 P86 R0
M73 Q86 S0
G1 X126.560 Y114.828 E0.01500
;WIPE_START
G1 F8640.000
G1 X126.172 Y113.541 E-0.31049
;WIPE_END
G1 E-0.48951 F2100.000
G1 Z0.600 F10800.000
G1 X115.204 Y109.866
M73 P87 R0
G1 Z0.200
M73 Q87 S0
G1 E0.80000 F2100.000
;WIDTH:0.116625
G1 F1200.000
G1 X115.369 Y108.988 E0.00548
G1 X115.431 Y108.961 E0.00042
;WIPE_START
G1 F8640.000
G1 X115.369 Y108.988 E-0.01569
G1 X115.204 Y109.866 E-0.20640
;WIPE_END
G1 E-0.57790 F2100.000
G1 Z0.600 F10800.000
G1 X119.049 Y95.799
G1 Z0.200
G1 E0.80000 F2100.000
;WIDTH:0.140756
G1 F1200.000
G1 X118.748 Y95.572 E0.00307
;WIDTH:0.234663
M73 P88 R0
G1 X118.249 Y95.195 E0.00997
;WIDTH:0.37394
M73 Q88 S0
G1 X117.916 Y94.944 E0.01147
G1 X117.956 Y94.278 F10800.000
;WIDTH:0.22523
G1 F1200.000
G1 X115.724 Y92.027 E0.04805
;WIDTH:0.18126
G1 X113.492 Y89.776 E0.03646
;WIDTH:0.137291
G1 X111.260 Y87.525 E0.02487
;WIPE_START
G1 F8640.000
G1 X113.492 Y89.776 E-0.73196
;WIPE_END
G1 E-0.06804 F2100.000
G1 Z0.600 F10800.000
M73 P89 R0
M73 Q89 S0
G1 X107.867 Y84.233
G1 Z0.200
G1 E0.80000 F2100.000
;WIDTH:0.26888
G1 F1200.000
G1 X107.797 Y84.089 E0.00301
;WIDTH:0.247404
G1 X107.736 Y83.942 E0.00270
;WIDTH:0.194394
G1 X107.681 Y83.807 E0.00183
;WIDTH:0.146708
G1 X107.626 Y83.672 E0.00126
;WIDTH:0.0990207
G1 X107.610 Y83.640 E0.00017
;WIPE_START
G1 F8640.000
G1 X107.626 Y83.672 E-0.00850
;WIPE_END
G1 E-0.79150 F2100.000
G1 Z0.600 F10800.000
G1 X103.521 Y87.532
G1 Z0.200
M73 P90 R0
G1 E0.80000 F2100.000
;WIDTH:0.131536
M73 Q90 S0
G1 F1200.000
G1 X103.597 Y87.623 E0.00087
;WIDTH:0.17259
G1 X103.902 Y87.978 E0.00504
G1 X104.154 Y88.838 F10800.000
;WIDTH:0.100449
G1 F1200.000
G1 X104.773 Y90.784 E0.00977
;WIPE_START
G1 F8640.000
G1 X104.154 Y88.838 E-0.47150
;WIPE_END
G1 E-0.32850 F2100.000
G1 Z0.600 F10800.000
G1 X136.465 Y101.227
M73 P91 R0
M73 Q91 S0
G1 Z0.200
G1 E0.80000 F2100.000
;WIDTH:0.10087
G1 F1200.000
G1 X136.208 Y101.163 E0.00127
;WIPE_START
G1 F8640.000
G1 X136.465 Y101.227 E-0.06106
;WIPE_END
G1 E-0.73894 F2100.000
G1 Z0.600 F10800.000
G1 X119.333 Y126.412
M73 Q92 S0
G1 Z0.200
M73 P92 R0
G1 E0.80000 F2100.000
;WIDTH:0.136482
G1 F1200.000
G1 X119.125 Y125.890 E0.00437
G1 X119.124 Y125.890 F10800.000
;WIDTH:0.205637
G1 F1200.000
G1 X119.332 Y126.412 E0.00760
; stop printing object body6968374 id:0 copy 0
;WIPE_START
G1 F8640.000;_WIPE
G1 X119.124 Y125.890 E-0.12975
;WIPE_END
G1 E-0.67025 F2100.000
G1 Z0.600 F10800.000
;TYPE:Custom
; Filament-specific end gcode
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M907 E538 ; reset extruder motor current
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.2 ; Move print head up
M73 P95 R0
M73 Q96 S0
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 28.91
; filament used [cm3] = 0.07
; filament used [g] = 0.09
; filament cost = 0.00
; total filament used [g] = 0.09
; total filament cost = 0.00
; estimated printing time (normal mode) = 1m 10s
; estimated printing time (silent mode) = 1m 11s

; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 30.24
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusament PLA"
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 50
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 15
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.9.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 215
; template_custom_gcode = 
; thin_walls = 0
; threads = 16
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
