; generated by PrusaSlicer 2.3.0+win64 on 2021-05-20 at 14:52:17 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R1
M73 Q0 S1
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.9.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
M73 P5 R1
M73 Q5 S1
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95

; Don't change E values below. Excessive value can damage the printer.
M907 E430 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P9 R1
M73 Q9 S1
G1 E-0.80000 F2100.000
G1 Z0.400 F10800.000
;AFTER_LAYER_CHANGE
;0.2
G1 X83.734 Y69.302
M73 P10 R1
M73 Q10 S1
G1 Z0.200
G1 E0.80000 F2100.000
M204 S1000
;TYPE:Skirt
;WIDTH:0.42
G1 F1200.000
G1 X85.981 Y66.959 E0.10179
M73 Q11 S1
G1 X92.158 Y61.287 E0.26296
M73 P11 R1
G1 X95.163 Y59.052 E0.11743
G1 X98.401 Y57.140 E0.11789
M73 P12 R1
M73 Q12 S1
G1 X100.306 Y56.219 E0.06634
G1 X102.276 Y55.409 E0.06680
G1 X104.291 Y54.718 E0.06680
G1 X106.330 Y54.154 E0.06634
G1 X108.399 Y53.713 E0.06634
M73 Q13 S1
G1 X110.506 Y53.394 E0.06680
G1 X112.628 Y53.202 E0.06680
M73 P13 R1
G1 X114.757 Y53.139 E0.06680
G1 X118.132 Y53.302 E0.10593
G1 X121.461 Y53.783 E0.10547
M73 Q14 S1
G1 X162.328 Y62.343 E1.30918
M73 P16 R1
M73 Q17 S1
G1 X164.536 Y62.900 E0.07140
M73 P17 R1
G1 X166.690 Y63.593 E0.07094
G1 X168.795 Y64.422 E0.07094
G1 X170.856 Y65.391 E0.07140
G1 X172.686 Y66.393 E0.06541
M73 Q18 S1
G1 X174.454 Y67.501 E0.06541
G1 X176.141 Y68.703 E0.06495
M73 P18 R1
G1 X177.767 Y70.011 E0.06541
G1 X179.312 Y71.412 E0.06541
G1 X180.772 Y72.902 E0.06541
G1 X182.142 Y74.476 E0.06541
G1 X183.417 Y76.127 E0.06541
M73 Q19 S1
G1 X184.592 Y77.851 E0.06541
M73 P19 R1
G1 X185.663 Y79.641 E0.06541
G1 X186.627 Y81.492 E0.06541
G1 X187.475 Y83.382 E0.06495
G1 X188.216 Y85.332 E0.06541
G1 X188.840 Y87.323 E0.06541
M73 Q20 S1
G1 X189.345 Y89.347 E0.06541
G1 X189.729 Y91.383 E0.06495
M73 P20 R1
G1 X190.009 Y93.613 E0.07048
G1 X190.147 Y95.842 E0.07002
G1 X190.143 Y98.090 E0.07048
G1 X189.996 Y100.333 E0.07048
M73 Q21 S1
G1 X189.708 Y102.562 E0.07048
G1 X189.278 Y104.769 E0.07048
M73 P21 R1
G1 X188.713 Y106.929 E0.07002
G1 X188.008 Y109.064 E0.07048
G1 X186.722 Y112.124 E0.10409
G1 X185.155 Y115.051 E0.10409
M73 P22 R1
M73 Q22 S1
G1 X176.954 Y127.841 E0.47638
M73 P23 R1
M73 Q23 S1
G1 X175.743 Y129.594 E0.06680
G1 X154.905 Y155.858 E1.05120
M73 P25 R1
M73 Q25 S1
G1 X153.151 Y157.857 E0.08337
M73 P26 R1
M73 Q26 S1
G1 X151.253 Y159.718 E0.08337
G1 X149.289 Y161.377 E0.08061
G1 X147.210 Y162.890 E0.08061
G1 X145.026 Y164.247 E0.08061
G1 X142.750 Y165.442 E0.08061
M73 P27 R1
M73 Q27 S1
G1 X140.393 Y166.469 E0.08061
G1 X137.967 Y167.321 E0.08061
G1 X135.501 Y167.992 E0.08015
G1 X132.978 Y168.486 E0.08061
G1 X130.279 Y168.807 E0.08521
M73 P28 R1
M73 Q28 S1
G1 X127.578 Y168.920 E0.08475
G1 X124.862 Y168.825 E0.08521
G1 X122.176 Y168.524 E0.08475
G1 X119.520 Y168.019 E0.08475
G1 X116.911 Y167.312 E0.08475
M73 P29 R1
M73 Q29 S1
G1 X114.363 Y166.409 E0.08475
G1 X111.879 Y165.307 E0.08521
G1 X109.842 Y164.224 E0.07232
G1 X107.868 Y163.003 E0.07278
G1 X105.990 Y161.664 E0.07232
M73 Q30 S1
G1 X104.192 Y160.196 E0.07278
M73 P30 R1
G1 X102.525 Y158.644 E0.07140
G1 X95.275 Y151.338 E0.32273
M73 P31 R1
M73 Q31 S1
G1 X93.117 Y148.932 E0.10133
G1 X91.262 Y146.449 E0.09718
G1 X89.631 Y143.813 E0.09718
G1 X88.238 Y141.045 E0.09718
M73 P32 R1
M73 Q32 S1
G1 X87.092 Y138.165 E0.09718
G1 X76.403 Y102.481 E1.16795
M73 P35 R1
M73 Q35 S1
G1 X75.843 Y100.304 E0.07048
G1 X75.425 Y98.110 E0.07002
G1 X75.175 Y96.187 E0.06081
G1 X75.031 Y94.268 E0.06035
G1 X74.992 Y92.329 E0.06081
G1 X75.059 Y90.391 E0.06081
M73 P36 R1
M73 Q36 S1
G1 X75.233 Y88.459 E0.06081
G1 X75.512 Y86.540 E0.06081
G1 X75.892 Y84.653 E0.06035
G1 X76.379 Y82.776 E0.06081
G1 X76.967 Y80.928 E0.06081
G1 X77.651 Y79.128 E0.06035
G1 X78.431 Y77.369 E0.06035
M73 P37 R1
M73 Q37 S1
G1 X79.313 Y75.642 E0.06081
G1 X80.281 Y73.978 E0.06035
G1 X81.346 Y72.357 E0.06081
G1 X82.498 Y70.797 E0.06081
G1 X83.696 Y69.349 E0.05893
; printing object body4005343 id:0 copy 0
;WIPE_START
G1 F8640.000
G1 X85.970 Y66.970 E-0.76000
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
M73 P38 R1
M73 Q38 S1
G1 X129.454 Y103.311
G1 Z0.200
M73 Q39 S1
G1 E0.80000 F2100.000
;TYPE:Perimeter
G1 F1200.000
G1 X130.599 Y103.053 E0.03680
M73 P39 R1
G1 X130.583 Y103.600 E0.01715
G1 X129.512 Y103.326 E0.03466
;WIPE_START
G1 F8640.000
G1 X130.599 Y103.053 E-0.25874
G1 X130.583 Y103.600 E-0.12630
G1 X129.512 Y103.326 E-0.25528
;WIPE_END
G1 E-0.15968 F2100.000
G1 Z0.600 F10800.000
G1 X128.026 Y102.834
G1 Z0.200
G1 E0.80000 F2100.000
G1 F1200.000
G1 X127.153 Y102.313 E0.03187
M73 Q40 S1
G1 X125.162 Y101.197 E0.07156
M73 P40 R1
G1 X125.693 Y100.513 E0.02713
G1 X127.983 Y102.791 E0.10129
;WIPE_START
G1 F8640.000
G1 X127.153 Y102.313 E-0.22129
G1 X125.162 Y101.197 E-0.52698
G1 X125.193 Y101.157 E-0.01173
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X128.863 Y103.527
M73 Q41 S1
G1 Z0.200
G1 E0.80000 F2100.000
M73 P41 R1
G1 F1200.000
G1 X129.012 Y103.423 E0.00572
G1 X128.998 Y103.414 E0.00053
G1 X129.359 Y103.333 E0.01161
G1 X128.945 Y103.770 E0.01888
G1 X128.882 Y103.584 E0.00617
G1 X129.282 Y103.963 F10800.000
;TYPE:External perimeter
G1 F1200.000
G1 X129.515 Y103.716 E0.01063
G1 X141.814 Y106.861 E0.39801
M73 P42 R1
M73 Q42 S1
G1 X143.784 Y107.385 E0.06392
G1 X135.013 Y120.942 E0.50626
M73 P43 R1
M73 Q43 S1
G1 X134.498 Y120.872 E0.01630
G1 X129.184 Y104.067 E0.55262
M73 P45 R1
M73 Q45 S1
G1 X129.241 Y104.006 E0.00262
G1 X129.080 Y103.691 F10800.000
G1 X128.540 Y103.749
G1 F1200.000
G1 X129.175 Y105.621 E0.06196
G1 X133.604 Y119.633 E0.46079
M73 P46 R1
M73 Q46 S1
G1 X133.948 Y120.827 E0.03895
G1 X133.535 Y121.150 E0.01643
G1 X124.031 Y115.296 E0.35000
M73 P47 R1
M73 Q47 S1
G1 X123.166 Y114.809 E0.03110
G1 X117.618 Y111.386 E0.20440
M73 Q48 S1
G1 X128.491 Y103.784 E0.41598
M73 P48 R1
M73 Q49 S1
G1 X128.872 Y103.526 F10800.000
;WIPE_START
G1 F8640.000
G1 X129.175 Y105.621 E-0.45259
M73 P49 R1
G1 X129.576 Y106.890 E-0.30741
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X123.228 Y115.244
G1 Z0.200
G1 E0.80000 F2100.000
G1 F1200.000
G1 X132.982 Y121.252 E0.35920
M73 P50 R1
M73 Q50 S1
G1 X133.635 Y121.630 E0.02364
G1 X133.574 Y122.139 E0.01609
G1 X123.358 Y125.482 E0.33704
M73 P51 R1
M73 Q51 S1
G1 X121.334 Y126.108 E0.06641
G1 X122.825 Y117.206 E0.28302
M73 P52 R1
M73 Q52 S1
G1 X123.008 Y116.228 E0.03119
G1 X123.215 Y115.303 E0.02973
G1 X123.397 Y114.881 F10800.000
;WIPE_START
G1 F8640.000
G1 X126.026 Y117.015 E-0.76000
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X133.897 Y121.346
M73 P53 R1
M73 Q53 S1
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:Perimeter
G1 F1200.000
G1 X134.182 Y121.123 E0.01132
G1 X134.210 Y121.213 E0.00296
G1 X134.817 Y121.296 E0.01921
G1 X134.421 Y121.911 E0.02295
G1 X133.963 Y122.059 E0.01508
G1 X134.039 Y121.428 E0.01995
G1 X133.949 Y121.376 E0.00325
;WIPE_START
G1 F8640.000
G1 X134.182 Y121.123 E-0.07923
G1 X134.210 Y121.213 E-0.02183
G1 X134.817 Y121.296 E-0.14145
G1 X134.421 Y121.911 E-0.16900
G1 X133.963 Y122.059 E-0.11107
G1 X134.039 Y121.428 E-0.14694
G1 X133.949 Y121.376 E-0.02396
;WIPE_END
G1 E-0.10652 F2100.000
G1 Z0.600 F10800.000
M73 Q54 S1
G1 X126.701 Y124.825
M73 P54 R1
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:External perimeter
G1 F1200.000
G1 X126.701 Y130.983 E0.19307
M73 P54 R0
G1 X126.240 Y131.173 E0.01566
G1 X125.370 Y130.335 E0.03787
M73 P55 R0
M73 Q55 S0
G1 X121.538 Y126.475 E0.17053
G1 X125.802 Y125.090 E0.14057
G1 X126.644 Y124.842 E0.02751
G1 X127.099 Y124.784 F10800.000
;WIPE_START
G1 F8640.000
G1 X126.675 Y128.134 E-0.76000
;WIPE_END
M73 P56 R0
M73 Q56 S0
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X126.692 Y131.395
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:Perimeter
G1 F1200.000
G1 X126.710 Y131.742 E0.01089
G1 X126.486 Y131.479 E0.01080
G1 X126.636 Y131.418 E0.00508
;WIPE_START
G1 F8640.000
G1 X126.710 Y131.742 E-0.07672
G1 X126.486 Y131.479 E-0.07956
G1 X126.636 Y131.418 E-0.03743
;WIPE_END
G1 E-0.60630 F2100.000
G1 Z0.600 F10800.000
G1 X111.857 Y94.584
M73 P57 R0
M73 Q57 S0
G1 Z0.200
G1 E0.80000 F2100.000
G1 F1200.000
G1 X111.682 Y94.149 E0.01471
G1 X112.092 Y94.391 E0.01493
G1 X111.903 Y94.546 E0.00766
G1 X112.142 Y94.838 F10800.000
;TYPE:External perimeter
G1 F1200.000
G1 X112.467 Y94.571 E0.01317
G1 X115.730 Y96.354 E0.11658
M73 P58 R0
M73 Q58 S0
G1 X126.098 Y102.152 E0.37248
M73 P59 R0
M73 Q59 S0
G1 X126.964 Y102.639 E0.03113
G1 X128.318 Y103.448 E0.04946
G1 X117.348 Y111.107 E0.41949
M73 P60 R0
M73 Q60 S0
G1 X113.895 Y100.618 E0.34621
M73 P61 R0
M73 Q61 S0
G1 X112.415 Y96.054 E0.15046
G1 X112.079 Y94.889 E0.03800
G1 X112.096 Y94.876 E0.00067
G1 X111.939 Y94.493 F10800.000
;WIPE_START
G1 F8640.000
G1 X112.467 Y94.571 E-0.11087
G1 X114.934 Y95.919 E-0.64913
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X115.530 Y95.815
M73 Q62 S0
G1 Z0.200
M73 P62 R0
G1 E0.80000 F2100.000
;TYPE:Perimeter
G1 F1200.000
G1 X115.556 Y95.802 E0.00091
;WIPE_START
G1 F8640.000
G1 X115.556 Y95.802 E0.00000
;WIPE_END
G1 E-0.80000 F2100.000
G1 Z0.600 F10800.000
G1 X115.654 Y91.259
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:External perimeter
G1 F1200.000
G1 X116.125 Y91.048 E0.01618
G1 X117.032 Y91.920 E0.03946
G1 X125.311 Y100.390 E0.37135
M73 P63 R0
M73 Q63 S0
G1 X124.827 Y101.014 E0.02477
G1 X115.948 Y96.047 E0.31897
M73 P64 R0
M73 Q64 S0
G1 X115.658 Y91.319 E0.14852
G1 X115.451 Y90.914 F10800.000
M73 Q65 S0
G1 X115.652 Y90.846
;TYPE:Perimeter
G1 F1200.000
G1 X115.605 Y90.429 E0.01316
M73 P65 R0
G1 X115.882 Y90.743 E0.01313
G1 X115.707 Y90.822 E0.00602
;WIPE_START
G1 F8640.000
G1 X115.605 Y90.429 E-0.09363
G1 X115.882 Y90.743 E-0.09667
G1 X115.707 Y90.822 E-0.04434
;WIPE_END
G1 E-0.56536 F2100.000
G1 Z0.600 F10800.000
G1 X130.979 Y102.968
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:External perimeter
G1 F1200.000
G1 X152.744 Y98.062 E0.69957
M73 P67 R0
M73 Q67 S0
G1 X152.985 Y98.406 E0.01315
G1 X146.990 Y107.703 E0.34686
M73 P68 R0
M73 Q68 S0
G1 X146.264 Y107.551 E0.02325
G1 X144.812 Y107.183 E0.04697
G1 X143.352 Y106.851 E0.04694
G1 X130.958 Y103.680 E0.40112
M73 P69 R0
M73 Q69 S0
G1 X130.977 Y103.028 E0.02044
G1 X130.763 Y102.631 F10800.000
;WIPE_START
G1 F8640.000
G1 X134.186 Y102.296 E-0.76000
;WIPE_END
M73 P70 R0
M73 Q70 S0
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X153.150 Y97.984
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:Perimeter
G1 F1200.000
G1 X153.296 Y97.942 E0.00478
G1 X153.205 Y98.063 E0.00476
G1 X153.184 Y98.033 E0.00115
;WIPE_START
G1 F8640.000
G1 X153.296 Y97.942 E-0.03337
G1 X153.205 Y98.063 E-0.03503
G1 X153.184 Y98.033 E-0.00845
;WIPE_END
G1 E-0.72315 F2100.000
G1 Z0.600 F10800.000
M73 Q71 S0
G1 X128.800 Y103.072
M73 P71 R0
G1 Z0.200
G1 E0.80000 F2100.000
;TYPE:External perimeter
G1 F1200.000
G1 X152.410 Y97.752 E0.75884
M73 P73 R0
M73 Q73 S0
G1 X152.908 Y97.662 E0.01587
G1 X153.411 Y97.516 E0.01641
G1 X153.873 Y97.323 E0.01570
G1 X154.333 Y97.222 E0.01474
G1 X154.081 Y97.614 E0.01459
G1 X153.741 Y97.977 E0.01562
G1 X153.428 Y98.395 E0.01634
G1 X153.170 Y98.828 E0.01583
G1 X147.509 Y107.595 E0.32719
M73 P74 R0
M73 Q74 S0
G1 X147.092 Y108.170 E0.02227
G1 X144.240 Y107.422 E0.09248
G1 X143.281 Y108.857 E0.05412
M73 Q75 S0
G1 X134.665 Y122.228 E0.49873
M73 P76 R0
M73 Q76 S0
G1 X127.054 Y124.700 E0.25093
G1 X127.078 Y125.465 E0.02399
G1 X127.078 Y130.687 E0.16372
M73 P77 R0
M73 Q77 S0
G1 X127.060 Y131.166 E0.01504
G1 X127.079 Y131.660 E0.01552
G1 X127.151 Y132.153 E0.01560
G1 X127.244 Y132.613 E0.01473
G1 X127.244 Y133.033 E0.01317
G1 X126.923 Y132.710 E0.01427
G1 X126.657 Y132.299 E0.01536
G1 X126.347 Y131.887 E0.01615
G1 X126.005 Y131.511 E0.01593
G1 X120.937 Y126.394 E0.22583
M73 P78 R0
M73 Q78 S0
G1 X121.118 Y125.119 E0.04038
G1 X122.519 Y116.753 E0.26594
G1 X122.784 Y115.015 E0.05512
M73 P79 R0
M73 Q79 S0
G1 X118.187 Y112.189 E0.16919
G1 X117.126 Y111.508 E0.03954
G1 X116.825 Y110.721 E0.02641
G1 X113.734 Y101.350 E0.30939
M73 P80 R0
M73 Q80 S0
G1 X111.534 Y94.793 E0.21686
G1 X111.346 Y94.320 E0.01597
G1 X111.116 Y93.861 E0.01610
G1 X110.874 Y93.437 E0.01530
G1 X110.736 Y93.025 E0.01363
M73 P81 R0
M73 Q81 S0
G1 X111.116 Y93.230 E0.01355
G1 X111.492 Y93.540 E0.01527
G1 X111.905 Y93.845 E0.01611
G1 X112.346 Y94.103 E0.01603
G1 X112.791 Y94.322 E0.01554
G1 X115.146 Y95.612 E0.08420
G1 X115.532 Y95.367 E0.01434
G1 X115.312 Y91.819 E0.11146
G1 X115.275 Y90.863 E0.03000
G1 X115.219 Y90.371 E0.01554
G1 X115.007 Y89.436 E0.03004
G1 X114.985 Y89.053 E0.01204
G1 X115.463 Y89.567 E0.02203
G1 X115.692 Y89.939 E0.01368
M73 P82 R0
M73 Q82 S0
G1 X116.020 Y90.341 E0.01628
G1 X116.369 Y90.708 E0.01585
G1 X128.758 Y103.030 E0.54787
M73 P83 R0
M73 Q83 S0
G1 X128.960 Y103.439 F10800.000
;WIPE_START
G1 F8640.000
G1 X131.970 Y102.313 E-0.76000
;WIPE_END
G1 E-0.04000 F2100.000
G1 Z0.600 F10800.000
G1 X128.919 Y104.073
G1 Z0.200
M73 P84 R0
G1 E0.80000 F2100.000
;TYPE:Gap fill
;WIDTH:0.144326
M73 Q84 S0
G1 F1200.000
G1 X129.402 Y105.547 E0.01308
G1 X133.834 Y119.565 E0.12396
;WIDTH:0.177096
M73 P85 R0
M73 Q85 S0
G1 X134.222 Y120.852 E0.01500
;WIPE_START
G1 F8640.000
G1 X133.834 Y119.565 E-0.31049
;WIPE_END
G1 E-0.48951 F2100.000
G1 Z0.600 F10800.000
G1 X122.866 Y115.890
G1 Z0.200
M73 P86 R0
M73 Q86 S0
G1 E0.80000 F2100.000
;WIDTH:0.116625
G1 F1200.000
G1 X123.031 Y115.012 E0.00548
G1 X123.093 Y114.985 E0.00042
;WIPE_START
G1 F8640.000
G1 X123.031 Y115.012 E-0.01569
G1 X122.866 Y115.890 E-0.20640
;WIPE_END
G1 E-0.57790 F2100.000
G1 Z0.600 F10800.000
G1 X126.711 Y101.823
G1 Z0.200
G1 E0.80000 F2100.000
;WIDTH:0.140756
M73 P87 R0
G1 F1200.000
G1 X126.410 Y101.596 E0.00307
;WIDTH:0.234663
M73 Q87 S0
G1 X125.911 Y101.219 E0.00997
;WIDTH:0.37394
G1 X125.578 Y100.968 E0.01147
G1 X125.618 Y100.302 F10800.000
;WIDTH:0.22523
G1 F1200.000
G1 X123.386 Y98.051 E0.04805
;WIDTH:0.18126
G1 X121.154 Y95.800 E0.03646
;WIDTH:0.137291
G1 X118.922 Y93.549 E0.02487
;WIPE_START
G1 F8640.000
G1 X121.154 Y95.800 E-0.73196
;WIPE_END
M73 P88 R0
M73 Q88 S0
G1 E-0.06804 F2100.000
G1 Z0.600 F10800.000
G1 X115.529 Y90.257
G1 Z0.200
G1 E0.80000 F2100.000
;WIDTH:0.26888
G1 F1200.000
G1 X115.459 Y90.113 E0.00301
;WIDTH:0.247404
G1 X115.398 Y89.966 E0.00270
;WIDTH:0.194394
G1 X115.343 Y89.831 E0.00183
;WIDTH:0.146708
G1 X115.288 Y89.696 E0.00126
;WIDTH:0.0990207
G1 X115.272 Y89.664 E0.00017
;WIPE_START
G1 F8640.000
G1 X115.288 Y89.696 E-0.00850
;WIPE_END
G1 E-0.79150 F2100.000
G1 Z0.600 F10800.000
G1 X111.183 Y93.556
M73 P89 R0
M73 Q89 S0
G1 Z0.200
G1 E0.80000 F2100.000
;WIDTH:0.131536
G1 F1200.000
G1 X111.259 Y93.647 E0.00087
;WIDTH:0.17259
G1 X111.564 Y94.002 E0.00504
G1 X111.816 Y94.862 F10800.000
;WIDTH:0.100449
G1 F1200.000
G1 X112.435 Y96.808 E0.00977
;WIPE_START
G1 F8640.000
G1 X111.816 Y94.862 E-0.47150
;WIPE_END
G1 E-0.32850 F2100.000
G1 Z0.600 F10800.000
G1 X144.127 Y107.251
M73 P90 R0
M73 Q90 S0
G1 Z0.200
G1 E0.80000 F2100.000
;WIDTH:0.10087
G1 F1200.000
G1 X143.870 Y107.187 E0.00127
;WIPE_START
G1 F8640.000
G1 X144.127 Y107.251 E-0.06106
;WIPE_END
G1 E-0.73894 F2100.000
G1 Z0.600 F10800.000
G1 X126.995 Y132.436
M73 P91 R0
M73 Q91 S0
G1 Z0.200
G1 E0.80000 F2100.000
;WIDTH:0.136482
G1 F1200.000
G1 X126.787 Y131.914 E0.00437
G1 X126.786 Y131.914 F10800.000
;WIDTH:0.205637
G1 F1200.000
G1 X126.993 Y132.436 E0.00760
; stop printing object body4005343 id:0 copy 0
;WIPE_START
G1 F8640.000;_WIPE
G1 X126.786 Y131.914 E-0.12975
;WIPE_END
G1 E-0.67025 F2100.000
G1 Z0.600 F10800.000
;TYPE:Custom
; Filament-specific end gcode
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M907 E538 ; reset extruder motor current
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.2 ; Move print head up
M73 P95 R0
M73 Q95 S0
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 25.96
; filament used [cm3] = 0.06
; filament used [g] = 0.08
; filament cost = 0.00
; total filament used [g] = 0.08
; total filament cost = 0.00
; estimated printing time (normal mode) = 1m 6s
; estimated printing time (silent mode) = 1m 6s

; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 30.24
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusament PLA"
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 35
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 15
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.9.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 215
; template_custom_gcode = 
; thin_walls = 0
; threads = 16
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
